### PR TITLE
Fix png jpg tests

### PR DESCRIPTION
**Pull request by frantz**
Tests are currently failing fro png and jpeg. This should help.

### CODE REVIEW

**Comment by frantz** [comment]
Well it seems that you fix them at the same time :) What about that missing `break`? Was it intentional?

**Comment by 1000ch** [comment]
Thank you for PR :) and I'm sorry :(

>What about that missing break? Was it intentional?

Not intentional. I'll fix it soon. Thank you :+1:

**Comment by frantz** [comment]
Nice and thank for your work.

**Comment by 1000ch** [comment]
Done. Please check `v1.2.1`.

**Pull request closed without merging**
